stages:
  - test
  - docker-build

test:
  image: quay.imanuel.dev/dockerhub/library---golang:1.20-alpine
  stage: test
  script:
    - go vet .
    - go build -o ruehmkorf.com

docker-build:
  image: quay.imanuel.dev/dockerhub/library---docker:stable
  stage: docker-build
  services:
    - docker:dind
  before_script:
    - docker login -u "$QUAY_USER" -p "$QUAY_PASSWORD" quay.imanuel.dev
  script:
    - docker build --pull -t "quay.imanuel.dev/reemt/ruehmkorf.com:1.2.${CI_PIPELINE_IID}" -f ./Dockerfile .
    - docker tag "quay.imanuel.dev/reemt/ruehmkorf.com:1.2.${CI_PIPELINE_IID}" "quay.imanuel.dev/reemt/ruehmkorf.com:latest"
    - docker push "quay.imanuel.dev/reemt/ruehmkorf.com:1.2.${CI_PIPELINE_IID}"
    - docker push "quay.imanuel.dev/reemt/ruehmkorf.com:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      exists:
        - Dockerfile