workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

variables:
  IMAGE_TAG: 2.0.$CI_PIPELINE_IID

stages:
  - test
  - deploy

.base-docker:
  image: registry.ulbricht.casa/docker-images/buildah:latest
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - echo "$DOCKERHUB_PASSWORD" | buildah login -u "$DOCKERHUB_USER" --password-stdin docker.io

test:
  image: library/golang:1.25-alpine
  stage: test
  script:
    - go vet .
    - go build -o ruehmkorf.com

docker-build:
  stage: deploy
  extends: .base-docker
  variables:
    IMG: $CI_REGISTRY_IMAGE/$ARCH:$IMAGE_TAG
  script:
    - buildah build --platform=linux/$ARCH -t $IMG .
    - buildah push $IMG
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  parallel:
    matrix:
      - ARCH: amd64
      - ARCH: arm64
  tags:
    - runner-$ARCH

merge-manifests:
  stage: deploy
  extends: .base-docker
  needs:
    - job: docker-build
      artifacts: false
  script:
    - buildah manifest create $FQ_IMAGE_NAME
    - buildah manifest add $FQ_IMAGE_NAME docker://$CI_REGISTRY_IMAGE/amd64:$IMAGE_TAG
    - buildah manifest add $FQ_IMAGE_NAME docker://$CI_REGISTRY_IMAGE/arm64:$IMAGE_TAG
    - buildah manifest push --all $FQ_IMAGE_NAME
  parallel:
    matrix:
      - FQ_IMAGE_NAME: $CI_REGISTRY_IMAGE:latest
      - FQ_IMAGE_NAME: $CI_REGISTRY_IMAGE:$IMAGE_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

trigger-server:
  needs:
    - job: merge-manifests
  variables:
    TAG: $IMAGE_TAG
  stage: deploy
  trigger: server-management/main-server.ulbricht.casa/ruehmkorf.com
  rules:
    - if: $CI_COMMIT_BRANCH == "main"