stages:
  - test
  - deploy

test:
  image: harbor.ulbricht.casa/proxy/library/golang:1.21-alpine
  stage: test
  script:
    - go vet .
    - go build -o ruehmkorf.com

docker-build:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    pull_policy: always
    entrypoint: [""]
  before_script:
    - echo $KANIKO_HARBOR_ONLY > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "harbor.ulbricht.casa/reemt/ruehmkorf.com:1.2.${CI_PIPELINE_IID}"
      --destination "harbor.ulbricht.casa/reemt/ruehmkorf.com:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      exists:
        - Dockerfile