stages:
  - test
  - docker-build

test:
  image: harbor.ulbricht.casa/proxy/library/golang:1.21-alpine
  stage: test
  script:
    - go vet .
    - go build -o ruehmkorf.com

docker-build:
  image: harbor.ulbricht.casa/proxy/library/docker:dind
  stage: docker-build
  before_script:
    - docker login -u "$HARBOR_USER" -p "$HARBOR_PASSWORD" harbor.ulbricht.casa
  script:
    - docker build --pull -t "harbor.ulbricht.casa/reemt/ruehmkorf.com:1.2.${CI_PIPELINE_IID}" -f ./Dockerfile .
    - docker tag "harbor.ulbricht.casa/reemt/ruehmkorf.com:1.2.${CI_PIPELINE_IID}" "harbor.ulbricht.casa/reemt/ruehmkorf.com:latest"
    - docker push "harbor.ulbricht.casa/reemt/ruehmkorf.com:1.2.${CI_PIPELINE_IID}"
    - docker push "harbor.ulbricht.casa/reemt/ruehmkorf.com:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      exists:
        - Dockerfile