version: "3"
services:
  ruehmkorfcom_db:
    container_name: ruehmkorfcom_db
    image: postgres:12.0-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ruehmkorf
      POSTGRES_PASSWORD: ruehmkorf
      POSTGRES_DB: ruehmkorf
    restart: always

  ruehmkorfcom_mailhog:
    container_name: ruehmkorfcom_mailhog
    image: mailhog/mailhog
    ports:
      - 1525:1025
      - 8525:8025
    restart: always