version: "3"
services:
  ruehmkorfcom_db:
    container_name: ruehmkorfcom_db
    image: harbor.ulbricht.casa/proxy/library/postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ruehmkorf
      POSTGRES_PASSWORD: ruehmkorf
      POSTGRES_DB: ruehmkorf
    restart: always