version: "3"
services:
  ruehmkorfcom_db:
    container_name: ruehmkorfcom_db
    image: quay.imanuel.dev/dockerhub/library---postgres:14.2-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ruehmkorf
      POSTGRES_PASSWORD: ruehmkorf
      POSTGRES_DB: ruehmkorf
    restart: always